# Generated by Django 4.1.3 on 2022-11-28 14:08

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=Application.models.expensive_calculation,
                        verbose_name="date published",
                    ),
                ),
            ],
        ),
    ]
