# Generated by Django 4.1.3 on 2022-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll", name="active", field=models.BooleanField(default=True),
        ),
    ]
